fix(ios): apple maps launchCoordinates launches maps with pin
pikaju/flutter-maps-launcher pull request #19
Opened 2021-08-17 20:14 UTC by kevinpthorne

Running the following only centers the map on iOS Apple Maps:
```
MapsLauncher.launchCoordinates(
      mylat,
      mylng,
    );
```

Changing the Apple Maps URL creation to use `q` instead of `ll` drops the pin as hoped for.

I tried using `sll` [as documented](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html) but it just refused to work. I would like for someone else to verify this, though.

2021-08-20 08:09 UTC, fettespferd requested changes
Functionality is not working for me on ios with your changes :(

2021-08-23 17:13 UTC, kevinpthorne commented
Could I get a screenshot? Is the `launchCoordinates` supposed to drop a pin on the coords. given or not? I guess this is also a question of intended functionality.

2021-10-04 11:28 UTC, levitanong commented
According to apple documentation, you need to have BOTH `q` AND `ll` set to place a pin. 

> The ll parameter can also represent a pin location when you use the q parameter to specify a name.

So if you want to always place a pin (and I think you usually do), the solution would be to use `ll` just as before, and if no label is set for `q`, stringify the coordinates to pass it again as `q`.

2022-07-19 14:01 UTC, Aristidios commented
Same issue on iOS search with coordinates doesn't place a pin on map

2022-12-20 00:08 UTC, Doddlin commented
+1 for adding this, perhaps as a conditional option to be added, a pin just feels like a nice addition

2023-02-08 17:58 UTC, pikaju commented
Hey, I'm a bit late to the party, but unfortunately I can't test anything because I don't have an Apple device. Isn't it enough to specify a label for the pin as the third parameter of `launchCoordinates`?

2023-02-08 18:49 UTC, Doddlin commented
Actually yes, the pin is now added in iOS Maps. I am using this code:

`ElevatedButton(
  onPressed: () => MapsLauncher.launchCoordinates(
    locationsViewModel.selectedLocation!.lat,
    locationsViewModel.selectedLocation!.long,
    locationsViewModel.selectedLocation!.locname),
  child: const Text("Åk till loppisen!"),
  style: const ButtonStyle(
  backgroundColor:
    MaterialStatePropertyAll<Color>(darkGreenColor),
    ),
),`

2023-02-09 10:55 UTC, pikaju commented
Alright, seeing as no one probably ever wants to open the map without a pin, I will add a default label. Hope this resolves the issue.

2023-02-09 10:55 UTC, closed without merging